### ISSUE TITLE
Can't build solution with VS after cloning repository

### ISSUE THREAD

**Issue by Insire** [SirJosh3917/Decorator#4]
To be able to build the solution, i have to remove the setting to sign the assembly like so

```
    <SignAssembly>false</SignAssembly>
```
Which is a minor inconvenience for me, but for other potential contributors or users of your library, it might keep them for contributing or using it.

I'm not not sure why you signed it in the first place. Regardless, [here ](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)is some reading material provided by MS on the matter.

Can you either remove the key or check it in aswell, so that people can just use your project?

**Comment by SirJosh3917** [comment]
Removed after consideration, thanks for providing that neat resource :+1:
